- id: pylint2-py39
  name: pylint V2 python 3.9
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:2-py39
  minimum_pre_commit_version: '2.9.2'
- id: pylint2-py310
  name: pylint V2 python 3.10
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:2-py310
  minimum_pre_commit_version: '2.9.2'
- id: pylint2-py311
  name: pylint V2 python 3.11
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:2-py311
  minimum_pre_commit_version: '2.9.2'
- id: pylint2-py312
  name: pylint V2 python 3.12
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:2-py312
  minimum_pre_commit_version: '2.9.2'
- id: pylint3-py39
  name: pylint V3 python 3.9
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:3-py39
  minimum_pre_commit_version: '2.9.2'
- id: pylint3-py310
  name: pylint V3 python 3.10
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:3-py310
  minimum_pre_commit_version: '2.9.2'
- id: pylint3-py311
  name: pylint V3 python 3.11
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:3-py311
  minimum_pre_commit_version: '2.9.2'
- id: pylint3-py312
  name: pylint V3 python 3.12
  language: docker_image
  require_serial: true
  types_or: [ python, pyi ]
  entry: magnati/pylint:3-py312
  minimum_pre_commit_version: '2.9.2'
